### ISSUE TITLE
How install from this source to Debian

### ISSUE THREAD

**Issue by ZerooCool** [lubuntu-team/pastebinit#1]
How install from this source to Debian ?
Then, i can add this to my wiki and use it.
https://wiki.visionduweb.fr/index.php?title=Gestion_des_logs#Utiliser_pastebinit

I need use the source, because the program from debian have a bug :
pastebinit fichier.txt

/usr/bin/pastebinit:42: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
 release = platform.linux_distribution()[0].lower()
/usr/bin/pastebinit:413: DeprecationWarning: pasteURLopener style of invoking requests is deprecated. Use newer urlopen functions/methods
 url_opener = pasteURLopener()

**Comment by wxl** [comment]
1.5.1 fixes this, which is available in Debian testing and beyond.
