### ISSUE TITLE
How install from this source to Debian ?

### ISSUE THREAD

**Issue by ZerooCool** [lubuntu-team/pastebinit#3]
Can you update the best method for a new install from this repo from Github, to a Debian System ?

I did not see an explanation for compiling or installing this repository.

**Comment by wxl** [comment]
Your best bet would be to build to Debian binary from the source which includes all the Debian packaging. You can find this on [Salsa](https://salsa.debian.org/debian/pastebinit).

Also: you don't need compile Python.
