### ISSUE TITLE
contributing patches

### ISSUE THREAD

**Issue by bboozzoo** [lubuntu-team/pastebinit#6]
I'm trying to update the packaging of pastebinit for openSUSE and may need apply some patches. I understand the upstream has moved from LP pastebinit to https://phab.lubuntu.me/source/pastebinit but it's unclear where the patches should be submitted to. Some downstreams, eg. Fedora still pull from LP. Arch on the other hand uses https://github.com/felixonmars/pastebinit as upstream URL. Which of the repositories is it then?

**Comment by Unit193** [comment]
Howdy,

Well I'm hoping better two years late is better than never.  But going forward the goal is to maintain pastebinit in the more accessible repo https://github.com/pastebinit/pastebinit.  It was just tagged so Debian hasn't gotten it yet, but keep an eye out there for confirmation if you'd like.

~Unit 193

**Comment by teward** [comment]
The Lubuntu ownership of the package has changed, and now it's an open source collaborative effort here on GitHub at https://github.com/pastebinit/pastebinit

Patches should now be submitted there.
